[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

optimizer = true
optimizer_runs = 200

ignore = [
    'src/vendored/CompatibilityFallbackHandler.sol',
    'src/vendored/ISignatureValidator.sol'
]

[profile.default.model_checker]
contracts = { 'src/libraries/TWAPOrderMathLib.sol' = [ 'TWAPOrderMathLib' ] }
engine = 'chc'
targets = [
    'assert', 'underflow', 'overflow', 'divByZero', 'constantCondition', 'popEmptyArray', 'outOfBounds', 'balance'
]
timeout = 100000